// /etc/icinga2/conf.d/hosts/infra-vms.conf — AS215932 infrastructure VMs

object Host "dns" {
  address6 = "2a0c:b641:b50:2::10"
  display_name = "dns (Knot DNS)"

  check_command = "ping6"

  vars.os = "Debian"
  vars.site = "ovh1"
  vars.role = "infra"
  vars.ssh_port = 22
  vars.prom_instance_node = "[2a0c:b641:b50:2::10]:9100"
  vars.disks["disk /"] = { mountpoint = "/" }
}

object Host "api" {
  address6 = "2a0c:b641:b50:2::20"
  display_name = "api (hyrule-cloud + PostgreSQL)"

  check_command = "ping6"

  vars.os = "Debian"
  vars.site = "ovh1"
  vars.role = "infra"
  vars.ssh_port = 22
  vars.prom_instance_node = "[2a0c:b641:b50:2::20]:9100"
  vars.prom_instance_postgres = "[2a0c:b641:b50:2::20]:9187"
  vars.disks["disk /"] = { mountpoint = "/" }
}

object Host "web" {
  address6 = "2a0c:b641:b50:2::30"
  display_name = "web (hyrule-web)"

  check_command = "ping6"

  vars.os = "Debian"
  vars.site = "ovh1"
  vars.role = "infra"
  vars.ssh_port = 22
  vars.prom_instance_node = "[2a0c:b641:b50:2::30]:9100"
  vars.disks["disk /"] = { mountpoint = "/" }
}

object Host "proxy" {
  address6 = "2a0c:b641:b50:2::40"
  display_name = "proxy (Caddy TLS)"

  check_command = "ping6"

  vars.os = "Debian"
  vars.site = "ovh1"
  vars.role = "infra"
  vars.ssh_port = 22
  vars.prom_instance_node = "[2a0c:b641:b50:2::40]:9100"
  vars.disks["disk /"] = { mountpoint = "/" }
}

object Host "mon" {
  address6 = "::1"
  display_name = "mon (Monitoring)"

  check_command = "ping6"

  vars.os = "Debian"
  vars.site = "ovh1"
  vars.role = "infra"
  vars.ssh_port = 22
  vars.prom_instance_node = "[2a0c:b641:b50:2::50]:9100"
  vars.disks["disk /"] = { mountpoint = "/" }
}

object Host "vpn" {
  address6 = "2a0c:b641:b50:2::60"
  display_name = "vpn (WireGuard VPN)"

  check_command = "ping6"

  vars.os = "Debian"
  vars.site = "ovh1"
  vars.role = "infra"
  vars.ssh_port = 22
  vars.prom_instance_node = "[2a0c:b641:b50:2::60]:9100"
  vars.disks["disk /"] = { mountpoint = "/" }
}

object Host "xoa" {
  address6 = "2a0c:b641:b50:2::70"
  display_name = "xoa (Xen Orchestra)"

  check_command = "ping6"

  vars.os = "Debian"
  vars.site = "ovh1"
  vars.role = "infra"
  vars.ssh_port = 22
  vars.prom_instance_node = "[2a0c:b641:b50:2::70]:9100"
  vars.disks["disk /"] = { mountpoint = "/" }
}
