// /etc/icinga2/conf.d/hosts/routers.conf — AS215932 core routers

object Host "rtr.ovh1" {
  address6 = "2a0c:b641:b50::d"
  display_name = "rtr (OVH FR)"

  check_command = "ping6"

  vars.os = "Debian"
  vars.site = "ovh1"
  vars.role = "router"
  vars.has_frr = true
  vars.ssh_port = 22
  vars.underlay_address6 = "2001:41d0:303:48a::2"
  vars.prom_instance_node = "[2a0c:b641:b50:2::1]:9100"
  vars.prom_instance_frr = "[2a0c:b641:b50:2::1]:9342"
}

object Host "cr1.nl1" {
  address6 = "2a0c:b641:b50::a"
  display_name = "cr1.nl1 (Servperso NL)"

  check_command = "ping6"

  vars.os = "FreeBSD"
  vars.site = "nl1"
  vars.role = "router"
  vars.has_frr = true
  vars.ssh_port = 22
  vars.underlay_address6 = "2a0c:b640:8:69::1"
  vars.prom_instance_node = "[2a0c:b641:b50::a]:9100"
  vars.prom_instance_frr = "[2a0c:b641:b50::a]:9342"
}

object Host "cr1.de1" {
  address6 = "2a0c:b641:b50::b"
  display_name = "cr1.de1 (Servperso DE)"

  check_command = "ping6"

  vars.os = "FreeBSD"
  vars.site = "de1"
  vars.role = "router"
  vars.has_frr = true
  vars.ssh_port = 22
  vars.underlay_address6 = "2a0c:b640:10::213"
  vars.prom_instance_node = "[2a0c:b641:b50::b]:9100"
  vars.prom_instance_frr = "[2a0c:b641:b50::b]:9342"
}
