// /etc/icinga2/conf.d/hosts/routers.conf — AS215932 core routers

object Host "rtr.ovh1" {
  address6 = "2a0c:b641:b50::d"
  display_name = "rtr (OVH FR)"

  check_command = "ping6"

  vars.os = "Debian"
  vars.site = "ovh1"
  vars.role = "router"
  vars.has_frr = true
  vars.ssh_port = 22
}

object Host "cr1.nl1" {
  address6 = "2a0c:b641:b50::a"
  display_name = "cr1.nl1 (Servperso NL)"

  check_command = "ping6"

  vars.os = "FreeBSD"
  vars.site = "nl1"
  vars.role = "router"
  vars.has_frr = true
  vars.ssh_port = 22
}

object Host "cr1.de1" {
  address6 = "2a0c:b641:b50::b"
  display_name = "cr1.de1 (Servperso DE)"

  check_command = "ping6"

  vars.os = "FreeBSD"
  vars.site = "de1"
  vars.role = "router"
  vars.has_frr = true
  vars.ssh_port = 22
}
