; /usr/local/etc/wireguard/wg0.conf — cr1.ch1 -> rtr.ovh1 wg2
[Interface]
ListenPort = 1339
PrivateKey = <PRIVATE_KEY>

[Peer]
; rtr.ovh1 (OVH underlay endpoint)
PublicKey = 61i9efepALlk/+8bqtPSsVhJOuRam2F8/bbXv4VvgCI=
Endpoint = [2001:41d0:303:48a::2]:1339
AllowedIPs = ::/0
PersistentKeepalive = 30
