; /usr/local/etc/wireguard/wg1.conf — cr1.ch1 wg1 -> cr1.nl1 wg4
[Interface]
ListenPort = 1341
PrivateKey = <PRIVATE_KEY>

[Peer]
; cr1.nl1 (underlay endpoint)
PublicKey = VL/p/xcokXmEpfHlU7vDcSBALJHNMvkpAuB58KhljWI=
Endpoint = [2a0c:b640:8:69::1]:1341
AllowedIPs = ::/0
PersistentKeepalive = 30
