; /usr/local/etc/wireguard/wg2.conf — cr1.ch1 wg2 -> cr1.de1 wg2
[Interface]
ListenPort = 1342
PrivateKey = <PRIVATE_KEY>

[Peer]
; cr1.de1 (underlay endpoint)
PublicKey = k+nrsjm1pzIu79sQESJcSfr7ZzJWhaqoBGTeQ8suwHI=
Endpoint = [2a0c:b640:10::213]:1342
AllowedIPs = ::/0
PersistentKeepalive = 30
