---
- name: reload systemd
  systemd:
    daemon_reload: true

- name: restart noc-agent
  systemd:
    name: noc-agent
    state: restarted
    enabled: true
  when: noc_agent_pyproject.stat.exists | default(false)
  ignore_errors: "{{ ansible_check_mode }}"
