# /etc/acme-client.conf — managed by ansible/roles/mail_openbsd

authority letsencrypt {
	api url "https://acme-v02.api.letsencrypt.org/directory"
	account key "/etc/acme/letsencrypt-privkey.pem"
}

authority letsencrypt-staging {
	api url "https://acme-staging-v02.api.letsencrypt.org/directory"
	account key "/etc/acme/letsencrypt-staging-privkey.pem"
}

domain mail.as215932.net {
	domain key "/etc/ssl/private/mail.as215932.net.key"
	domain full chain certificate "/etc/ssl/mail.as215932.net.fullchain.pem"
	sign with letsencrypt
}
