# /etc/httpd.conf — managed by ansible/roles/mail_openbsd

server "mail.as215932.net" {
	listen on * port 80

	location "/.well-known/acme-challenge/*" {
		root "/acme"
		request strip 2
	}

	location * {
		block return 302 "https://mail.as215932.net$REQUEST_URI"
	}
}
