# /etc/mail/smtpd.conf — managed by ansible/roles/mail_openbsd

pki mail.as215932.net cert "/etc/ssl/mail.as215932.net.fullchain.pem"
pki mail.as215932.net key "/etc/ssl/private/mail.as215932.net.key"
pki mail.as215932.net dhe auto

smtp sub-addr-delim '+'

filter rspamd proc-exec "filter-rspamd"

table aliases file:/etc/mail/aliases

listen on all port 25  tls         pki "mail.as215932.net" filter "rspamd"
listen on all port 465 smtps       pki "mail.as215932.net" auth mask-src filter "rspamd"
listen on all port 587 tls-require pki "mail.as215932.net" auth mask-src filter "rspamd"

action "local" lmtp "/var/dovecot/lmtp" alias <aliases>
action "outbound" relay

match from any for domain "as215932.net" action "local"
match from local for local action "local"
match from any auth for any action "outbound"
