// /etc/icinga2/conf.d/services/postgres.conf — PostgreSQL health check

apply Service "postgres" {
  check_command = "pgsql"
  check_interval = 1m
  retry_interval = 30s

  vars.pgsql_hostname = "2a0c:b641:b50:2::20"
  vars.pgsql_port = 5432
  vars.pgsql_database = "hyrule"

  assign where host.vars.has_postgres
}
