---
- name: reload prometheus
  systemd:
    name: prometheus
    state: reloaded

- name: restart blackbox_exporter
  systemd:
    name: prometheus-blackbox-exporter
    state: restarted

- name: reload alertmanager
  systemd:
    name: prometheus-alertmanager
    state: reloaded

- name: restart node_exporter
  systemd:
    name: prometheus-node-exporter
    state: restarted

- name: reload systemd
  systemd:
    daemon_reload: true

- name: restart extmon-bgp-agent
  systemd:
    name: extmon-bgp-agent
    state: restarted
    daemon_reload: true

- name: restart extmon-diag-agent
  systemd:
    name: extmon-diag-agent
    state: restarted
    daemon_reload: true

- name: restart bgpalerter
  systemd:
    name: bgpalerter
    state: restarted
    daemon_reload: true
