---
all:
  children:
    linux:
      hosts:
        rtr:
          ansible_host: 2a0c:b641:b50:2::1
          ansible_user: root
        dns:
          ansible_host: 2a0c:b641:b50:2::10
        api:
          ansible_host: 2a0c:b641:b50:2::20
        web:
          ansible_host: 2a0c:b641:b50:2::30
        proxy:
          ansible_host: 2a0c:b641:b50:2::40
        mon:
          ansible_host: 2a0c:b641:b50:2::50
        vpn:
          ansible_host: 2a0c:b641:b50:2::60
        xoa:
          ansible_host: 2a0c:b641:b50:2::70
          ansible_user: root
        irc:
          ansible_host: 2a0c:b641:b50:2::80
        ns2:
          ansible_host: 2001:41d0:304:300::7bfb

    openbsd:
      hosts:
        mail:
          ansible_host: 2a0c:b641:b50:2::90

    freebsd:
      hosts:
        cr1-nl1:
          ansible_host: 2a0c:b641:b50::a
        cr1-de1:
          ansible_host: cr1-de1.servify.network

    routers:
      hosts:
        rtr:
        cr1-nl1:
        cr1-de1:

    infra_vms:
      hosts:
        dns:
        api:
        web:
        proxy:
        mon:
        vpn:
        xoa:
        irc:
        mail:

    public_facing:
      hosts:
        rtr:
        proxy:
        vpn:
        dns:
        ns2:
        mail:

    nameservers:
      hosts:
        dns:
        ns2:
