"""Commit, push, and optional draft-PR boundary for promoted worktrees."""

from __future__ import annotations

import os
import subprocess
from pathlib import Path
from typing import Any

from hyrule_engineering_loop.policy import validate_pr_remote


class PRBoundaryError(RuntimeError):
    """Raised when PR boundary safety checks fail."""


def _run(args: list[str], *, cwd: Path) -> subprocess.CompletedProcess[str]:
    completed = subprocess.run(
        args,
        cwd=cwd,
        capture_output=True,
        check=False,
        text=True,
    )
    if completed.returncode != 0:
        raise PRBoundaryError(completed.stderr.strip() or completed.stdout.strip())
    return completed


def _approved(state: dict[str, Any]) -> bool:
    return state.get("approval_decision") == "approved"


def _github_pr_enabled(create_github_pr: bool) -> bool:
    if create_github_pr:
        return True
    return os.environ.get("HYRULE_CREATE_GITHUB_PR", "0").lower() in {"1", "true", "yes"}


def _create_github_pr(
    *,
    worktree_path: Path,
    branch: str,
    title: str,
    body: str,
    enabled: bool,
) -> dict[str, Any]:
    if not _github_pr_enabled(enabled):
        return {"created": False, "url": None, "provider": "disabled"}

    completed = _run(
        [
            "gh",
            "pr",
            "create",
            "--draft",
            "--title",
            title,
            "--body",
            body,
            "--head",
            branch,
        ],
        cwd=worktree_path,
    )
    return {"created": True, "url": completed.stdout.strip(), "provider": "gh"}


def publish_promoted_worktrees(
    state: dict[str, Any],
    *,
    remote: str = "origin",
    commit_message: str | None = None,
    pr_title: str | None = None,
    pr_body: str | None = None,
    create_github_pr: bool = False,
) -> list[dict[str, Any]]:
    """Commit and push promoted worktrees after human approval."""
    validate_pr_remote(state, remote=remote)
    if not _approved(state):
        raise PRBoundaryError("approval_decision must be approved before PR publication")

    promotion_results = list(state.get("promotion_results", []))
    if not promotion_results:
        raise PRBoundaryError("promotion_results are required before PR publication")

    message = commit_message or state.get("commit_message") or f"{state['change_id']}: apply changes"
    title = pr_title or state.get("pr_title") or str(message)
    body = pr_body or state.get("pr_body") or "Generated by the Hyrule Engineering Loop."

    results: list[dict[str, Any]] = []
    for promotion in promotion_results:
        worktree_path = Path(str(promotion["worktree_path"]))
        branch = str(promotion["branch"])
        if not worktree_path.exists():
            raise PRBoundaryError(f"promoted worktree is missing: {worktree_path}")

        status = _run(["git", "status", "--porcelain"], cwd=worktree_path).stdout.strip()
        if not status:
            raise PRBoundaryError(f"promoted worktree has no changes: {worktree_path}")

        _run(["git", "add", "."], cwd=worktree_path)
        _run(["git", "commit", "-m", message], cwd=worktree_path)
        commit_sha = _run(["git", "rev-parse", "HEAD"], cwd=worktree_path).stdout.strip()
        _run(["git", "push", remote, f"HEAD:{branch}"], cwd=worktree_path)
        github_pr = _create_github_pr(
            worktree_path=worktree_path,
            branch=branch,
            title=title,
            body=body,
            enabled=create_github_pr,
        )

        results.append(
            {
                "repo": promotion["repo"],
                "branch": branch,
                "remote": remote,
                "commit": commit_sha,
                "pushed": True,
                "github_pr": github_pr,
            }
        )

    return results
