; /etc/wireguard/wg0.conf — rtr.ovh1 wg0 -> cr1.nl1 wg3
[Interface]
ListenPort = 1337
PrivateKey = <PRIVATE_KEY>

[Peer]
; cr1.nl1
PublicKey = yx1cxAkZqG065H+ali8OSaK7j2xobxlCObs1ymGd4zc=
Endpoint = [2a0c:b640:8:69::1]:1340
AllowedIPs = ::/0
PersistentKeepalive = 30
