; /etc/wireguard/wg1.conf — rtr.ovh1 wg1 -> cr1.de1 wg1
[Interface]
ListenPort = 1338
PrivateKey = <PRIVATE_KEY>

[Peer]
; cr1.de1
PublicKey = 09IpW/eDRkZLZU25yWtK+TtH8TfkQsC7etgndKW0A0s=
Endpoint = cr1.de1.servify.nl:1338
AllowedIPs = ::/0
PersistentKeepalive = 30
