; /etc/wireguard/wg2.conf — rtr.ovh1 wg2 -> cr1.ch1
[Interface]
ListenPort = 1339
PrivateKey = <PRIVATE_KEY>

[Peer]
; cr1.ch1
PublicKey = kXDLgAfQAV454SZrN8PrF1lNuiEdamAwJDend3x2jWQ=
Endpoint = [2a09:4c0:100:2d88::8898]:1339
AllowedIPs = ::/0
PersistentKeepalive = 30
