# /etc/wireguard/wg0.conf — vpn VM (WireGuard VPN server)
# Managed via wg-quick@wg0.service.
# VPN client subnet: 2a0c:b641:b50:3::/64
[Interface]
Address = 2a0c:b641:b50:3::1/64
ListenPort = 51820
PrivateKey = ALWuVCNhm/yfCIaJEo5qUhIoAJU6b/C/+Rm/6afRhXU=

[Peer]
# laptop
PublicKey = V3o15RmvfjbS/c7XeClcTWdUNFOWXu4aMK/U7v7tsQQ=
AllowedIPs = 2a0c:b641:b50:3::2/128
