---
- name: validate knot config
  command: "{{ knot_validate_cmd }} {{ knot_conf_path }}.new conf-check"
  changed_when: false
  listen: reload knot

- name: reload knot
  command: knotc reload
  changed_when: true
  listen: reload knot

- name: restart systemd-resolved
  systemd:
    name: systemd-resolved
    state: restarted
    daemon_reload: true

- name: reload systemd
  systemd:
    daemon_reload: true

- name: restart hyrule-dns-control
  systemd:
    name: hyrule-dns-control.service
    state: restarted
  when: knot_dns_control_enabled | bool

- name: restart hyrule-dns-observer
  systemd:
    name: hyrule-dns-observer.service
    state: restarted
  when: knot_ip_check_observer_enabled | bool
