#!/usr/bin/env python3
"""Regenerate docs/network-flows.md from the structured Ansible inventory.

Reads:
  ansible/inventory/group_vars/all.yml   -> peers, subnet constants, ops-prefix
  ansible/inventory/host_vars/<host>.yml -> host_meta, firewall_extra_rules,
                                            network_flows_outbound
  ansible/inventory/hosts.yml            -> inventory membership (validation)
  ansible/inventory/network_flows.yml    -> cross_cutting_flows, network_externals,
                                            doc-level notes

Writes a deterministic docs/network-flows.md. The doc is a build artifact:
run this script after changing any of the inputs and commit the result. The
render-freshness test (tests/iac/test_network_flows_render.py) fails if the
committed doc drifts from the structured data.

Dependencies: Python 3 standard library + PyYAML only.

Usage:
  python3 scripts/render-network-flows.py            # overwrite docs/network-flows.md
  python3 scripts/render-network-flows.py --output - # print to stdout
  python3 scripts/render-network-flows.py --check     # exit 1 if the doc is stale
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parents[1]
INVENTORY = REPO / "ansible" / "inventory"
DEFAULT_OUTPUT = REPO / "docs" / "network-flows.md"

GENERATED_HEADER = (
    "<!--\n"
    "DO NOT EDIT — generated by scripts/render-network-flows.py from\n"
    "ansible/inventory/. Run the script to regenerate.\n"
    "-->\n"
)

# Built-in from/to tokens that are not peers and not in network_externals.
BUILTIN_TOKENS = {"all", "public", "any"}

# Friendly labels for the group_vars/all.yml subnet/prefix constants, used when
# resolving a `{{ constant }}` reference in a firewall_extra_rules `src`.
CONSTANT_LABELS = {
    "infra_subnet": "infra subnet",
    "customer_subnet": "customer subnet",
    "vpn_clients_subnet": "vpn-clients",
    "loop_docker_subnet": "loop Docker subnet",
    "ops_prefix_v6": "ops-prefix",
    "ops_prefix_v4": "ops-prefix (v4)",
    "mgmt_v4": "mgmt v4",
    "legacy_infra_v4": "legacy infra v4",
    "as215932_prefix": "AS215932 prefix",
    "router_loopback_subnet": "router loopbacks",
    "wg_link_prefix": "wg links",
}

# Ordered (constant key, purpose) rows for the Subnets table. CIDR is pulled
# from group_vars/all.yml so the address stays single-sourced.
SUBNET_ROWS = [
    ("as215932_prefix", "AS215932 prefix (announced)"),
    ("router_loopback_subnet", "Router loopbacks (::a cr1-nl1, ::b cr1-de1, ::c cr1-ch1, ::d rtr)"),
    ("infra_subnet", "Infra subnet (rtr ::1, VMs ::10-::f0)"),
    ("vpn_clients_subnet", "VPN clients (routed via the vpn VM)"),
    ("loop_docker_subnet", "loop VM Docker bridge containers (routed GUA /64)"),
    ("wg_link_prefix", "WireGuard tunnel /127s (mesh links)"),
    ("customer_subnet", "Customer VM allocations (::c1 = ci-pr, the unprivileged PR runner)"),
    ("mgmt_v4", "Mgmt v4 (dom0 <-> XOA XAPI)"),
    ("legacy_infra_v4", "Legacy v4 DNAT targets on rtr"),
]

# Suffix appended to the Proto column to record the address family a rule scopes
# to. Unset family defaults to IPv6-only (the nftables/pf template default).
FAMILY_SUFFIX = {
    None: "",
    "ip6": "",
    "v6": "",
    "inet6": "",
    "ipv6": "",
    "ip": " (v4)",
    "inet": " (v4)",
    "ipv4": " (v4)",
    "both": " (v4+v6)",
}

NO_PORT_SORT = 10**9  # sort key for portless rules (icmp/ospf/any-port egress)

JINJA_RE = re.compile(r"^\{\{\s*(.+?)\s*\}\}(.*)$")


# --------------------------------------------------------------------------- #
# Loading
# --------------------------------------------------------------------------- #
def _load_yaml(path: Path):
    return yaml.safe_load(path.read_text()) or {}


def load_inventory(inventory: Path):
    group_vars = _load_yaml(inventory / "group_vars" / "all.yml")
    hosts_yml = _load_yaml(inventory / "hosts.yml")
    flows = _load_yaml(inventory / "network_flows.yml")
    host_vars = {}
    for hv in sorted((inventory / "host_vars").glob("*.yml")):
        host_vars[hv.stem] = _load_yaml(hv)
    return group_vars, hosts_yml, flows, host_vars


def inventory_hostnames(hosts_yml: dict) -> set:
    """Collect every hostname declared anywhere in hosts.yml groups."""
    names = set()

    def walk(node):
        if not isinstance(node, dict):
            return
        for group in node.values():
            if not isinstance(group, dict):
                continue
            for host in (group.get("hosts") or {}):
                names.add(host)
            walk(group.get("children"))

    walk(hosts_yml.get("all", {}).get("children", {}))
    # hosts.yml top-level may also nest groups directly under `all`.
    walk({"all": hosts_yml.get("all", {})})
    return names


# --------------------------------------------------------------------------- #
# Resolution helpers
# --------------------------------------------------------------------------- #
class Resolver:
    def __init__(self, group_vars: dict, externals: dict, host_names=None):
        self.peers = group_vars.get("peers", {})
        self.externals = externals or {}
        # Inventory hosts (host_meta hosts) — flow endpoints that are real hosts
        # but not in the peers address book (e.g. dom0, underlay-only).
        self.host_names = set(host_names or [])
        # reverse map: literal constant value -> friendly label (for literal src)
        self.literal_labels = {}
        for key, label in CONSTANT_LABELS.items():
            value = group_vars.get(key)
            if isinstance(value, str):
                self.literal_labels[value] = label

    def _peer_key(self, host: str):
        for candidate in (host, host.replace("-", "_"), host.replace("_", "-")):
            if candidate in self.peers:
                return candidate
        return None

    def peer_display(self, host: str) -> str:
        return host.replace("_", "-")

    def resolve_src_token(self, token: str) -> str:
        """Resolve one firewall_extra_rules `src` entry to a human label."""
        token = token.strip()
        if token.lower() == "any":
            return "any"
        m = JINJA_RE.match(token)
        if m:
            inner = m.group(1).strip()
            suffix = m.group(2).strip()  # e.g. "/128"; dropped for display
            if inner.startswith("peers."):
                parts = inner.split(".")
                if len(parts) >= 3:
                    _, host, field = parts[0], parts[1], parts[2]
                    key = self._peer_key(host)
                    if key is None:
                        raise ValueError(f"unknown peer in src: {token}")
                    name = self.peer_display(host)
                    qualifier = {
                        "ipv6": "",
                        "loopback": " loopback",
                        "underlay": " underlay",
                        "ipv4": " (v4)",
                        "mgmt_v4": " (mgmt v4)",
                    }.get(field, f" ({field})")
                    return f"{name}{qualifier}"
                raise ValueError(f"malformed peers ref: {token}")
            if inner in CONSTANT_LABELS:
                return CONSTANT_LABELS[inner]
            raise ValueError(f"unresolvable src reference: {token}")
        # literal address / CIDR
        return self.literal_labels.get(token, token)

    def resolve_src(self, src) -> str:
        if src is None:
            return "any"
        if isinstance(src, (list, tuple)):
            return ", ".join(self.resolve_src_token(str(s)) for s in src)
        return self.resolve_src_token(str(src))

    def validate_endpoint(self, token: str) -> str:
        """Validate a from/to token and return its display string."""
        if token in BUILTIN_TOKENS:
            return token
        if self._peer_key(token) is not None:
            return self.peer_display(token)
        if token in self.host_names:
            return token
        if token in self.externals:
            return token
        raise ValueError(f"unresolvable flow endpoint token: {token!r}")


# --------------------------------------------------------------------------- #
# Formatting helpers
# --------------------------------------------------------------------------- #
def format_port(port) -> str:
    if port is None:
        return "—"
    if isinstance(port, (list, tuple)):
        return ", ".join(str(p) for p in port)
    return str(port)


def port_sort_key(port) -> int:
    if port is None:
        return NO_PORT_SORT
    if isinstance(port, (list, tuple)):
        ints = [int(p) for p in port if str(p).isdigit()]
        return min(ints) if ints else NO_PORT_SORT
    s = str(port)
    if s.isdigit():
        return int(s)
    head = s.split("-")[0]
    return int(head) if head.isdigit() else NO_PORT_SORT


def format_proto(proto, family=None) -> str:
    base = str(proto) if proto is not None else "?"
    if family not in FAMILY_SUFFIX:
        # Unknown family value: surface it verbatim rather than silently drop.
        return f"{base} ({family})"
    return f"{base}{FAMILY_SUFFIX[family]}"


def md_table(headers, rows) -> list:
    out = ["| " + " | ".join(headers) + " |"]
    out.append("|" + "|".join("---" for _ in headers) + "|")
    for row in rows:
        out.append("| " + " | ".join(row) + " |")
    return out


# --------------------------------------------------------------------------- #
# Section renderers
# --------------------------------------------------------------------------- #
def host_ipv6(resolver: Resolver, host: str) -> str:
    key = resolver._peer_key(host)
    peer = resolver.peers.get(key, {}) if key else {}
    if peer.get("ipv6"):
        return f"`{peer['ipv6']}`"
    if peer.get("loopback"):
        return f"`{peer['loopback']}` (loopback)"
    return "—"


def host_ipv4(resolver: Resolver, host: str, meta: dict) -> str:
    if meta.get("ipv4"):
        return meta["ipv4"]
    key = resolver._peer_key(host)
    peer = resolver.peers.get(key, {}) if key else {}
    if peer.get("ipv4"):
        return f"`{peer['ipv4']}`"
    if peer.get("mgmt_v4"):
        return f"`{peer['mgmt_v4']}` (mgmt)"
    return "—"


def render_hosts_table(resolver, hosts, host_vars) -> list:
    rows = []
    for host in hosts:
        meta = host_vars[host]["host_meta"]
        rows.append([
            host,
            meta.get("os", "—"),
            host_ipv6(resolver, host),
            host_ipv4(resolver, host, meta),
            meta.get("role", "—"),
        ])
    return md_table(["Host", "OS", "IPv6 (overlay)", "IPv4", "Role"], rows)


def render_subnets_table(group_vars) -> list:
    rows = []
    for key, purpose in SUBNET_ROWS:
        cidr = group_vars.get(key)
        if cidr is None:
            continue
        rows.append([f"`{cidr}`", purpose])
    v6 = group_vars.get("ops_prefix_v6")
    v4 = group_vars.get("ops_prefix_v4")
    if v6 and v4:
        rows.append([f"`{v6}`, `{v4}`", "Ops-prefix (KPN home; SSH + AXFR allow)"])
    return md_table(["CIDR", "Purpose"], rows)


def synthesize_router_inbound(hv) -> list:
    """Inbound rules for FreeBSD/pf routers that live in the pf template, not
    `firewall_extra_rules`: external BGP (tcp/179 from each `pf_bgp_peers`) and
    the WireGuard underlay listeners (udp from each `pf_wg_ports`). Rendered as
    synthetic inbound rows so router BGP/WG paths are queryable like every other
    host's inbound. Not exhaustive — `pass quick on wg`, ICMP, and transit
    forwarding are described in the host's notes, not as discrete ports."""
    synthesized = []
    for peer in hv.get("pf_bgp_peers") or []:
        peer = str(peer).strip()
        if not peer or peer.startswith("[") or "placeholder" in peer.lower():
            continue  # commented-out / placeholder peer
        synthesized.append({"proto": "tcp", "dport": 179, "src": peer,
                            "family": "inet6", "comment": "External BGP (pf_bgp_peers)"})
    wg_ports = [p for p in (hv.get("pf_wg_ports") or []) if p is not None]
    if wg_ports:
        synthesized.append({"proto": "udp", "dport": list(wg_ports), "src": "any",
                            "comment": "WireGuard underlay tunnels (pf_wg_ports)"})
    return synthesized


def render_inbound_table(resolver, rules) -> list:
    entries = []
    for r in rules:
        frm = resolver.resolve_src(r.get("src"))
        proto = format_proto(r.get("proto"), r.get("family"))
        port = format_port(r.get("dport"))
        purpose = str(r.get("comment", "")).strip()
        entries.append((port_sort_key(r.get("dport")), r.get("proto") or "", frm, purpose,
                        [frm, proto, port, purpose]))
    entries.sort(key=lambda e: (e[0], e[1], e[2], e[3]))
    return md_table(["From", "Proto", "Port", "Purpose"], [e[4] for e in entries])


def render_outbound_table(resolver, flows) -> list:
    entries = []
    for f in flows:
        to = resolver.validate_endpoint(f["to"])
        proto = format_proto(f.get("proto"), f.get("family"))
        port = format_port(f.get("port"))
        purpose = str(f.get("purpose", "")).strip()
        entries.append((port_sort_key(f.get("port")), to, f.get("proto") or "", purpose,
                        [to, proto, port, purpose]))
    entries.sort(key=lambda e: (e[0], e[1], e[2], e[3]))
    return md_table(["To", "Proto", "Port", "Purpose"], [e[4] for e in entries])


def render_cross_cutting_table(resolver, flows, valid_hosts=frozenset()) -> list:
    entries = []
    for f in flows:
        frm = resolver.validate_endpoint(f["from"])
        to = resolver.validate_endpoint(f["to"])
        exc = f.get("except") or []
        if exc:
            if f["from"] != "all" and f["to"] != "all":
                raise ValueError(f"`except` is only valid on an `all` flow: {f!r}")
            for tok in exc:
                if valid_hosts and str(tok) not in valid_hosts:
                    raise ValueError(f"`except` token {tok!r} is not an inventory host: {f!r}")
            exc_label = f" (except {', '.join(str(t) for t in exc)})"
            if f["from"] == "all":
                frm += exc_label
            else:
                to += exc_label
        proto = format_proto(f.get("proto"), f.get("family"))
        port = format_port(f.get("port"))
        purpose = str(f.get("purpose", "")).strip()
        entries.append((frm, to, port_sort_key(f.get("port")), f.get("proto") or "",
                        [frm, to, proto, port, purpose]))
    entries.sort(key=lambda e: (e[0], e[1], e[2], e[3]))
    return md_table(["From", "To", "Proto", "Port", "Purpose"], [e[4] for e in entries])


def render_externals_table(externals) -> list:
    rows = []
    for token in sorted(externals):
        info = externals[token] or {}
        rows.append([f"`{token}`", info.get("name", "—"), info.get("note", "")])
    return md_table(["Token", "Endpoint", "Note"], rows)


# --------------------------------------------------------------------------- #
# Document assembly
# --------------------------------------------------------------------------- #
def render_document(group_vars, hosts_yml, flows, host_vars) -> str:
    externals = flows.get("network_externals", {}) or {}
    inv_hosts = inventory_hostnames(hosts_yml)
    hosts = sorted(h for h, hv in host_vars.items() if isinstance(hv, dict) and "host_meta" in hv)
    resolver = Resolver(group_vars, externals, host_names=inv_hosts or set(hosts))
    for host in hosts:
        if inv_hosts and host not in inv_hosts:
            raise ValueError(f"host_vars/{host}.yml has host_meta but is not in hosts.yml")

    lines = [GENERATED_HEADER.rstrip("\n"), ""]
    lines.append("# AS215932 — Network flows")
    lines.append("")
    lines.append(
        "This document is the canonical inventory of every traffic flow between hosts in "
        "AS215932. It is **generated** from the Ansible inventory — do not edit by hand."
    )
    lines.append("")
    lines.append("To change a flow, edit the structured data and re-run the renderer:")
    lines.append("")
    lines.append("- **inbound** — `firewall_extra_rules` in `ansible/inventory/host_vars/<host>.yml`")
    lines.append("- **outbound** — `network_flows_outbound` in the same file")
    lines.append("- **cross-cutting / external** — `ansible/inventory/network_flows.yml`")
    lines.append("- **host identity / subnets** — `host_meta` in host_vars and `peers`/subnet "
                 "constants in `ansible/inventory/group_vars/all.yml`")
    lines.append("")
    lines.append("Then run `python3 scripts/render-network-flows.py`. The freshness test "
                 "`tests/iac/test_network_flows_render.py` fails if this file drifts.")
    lines.append("")
    lines.append("---")
    lines.append("")

    # Hosts
    lines.append("## Hosts")
    lines.append("")
    lines.extend(render_hosts_table(resolver, hosts, host_vars))
    lines.append("")
    lines.append("dom0 is an XCP-NG hypervisor on the underlay only; it is not on the AS215932 "
                 "overlay and is not yet managed by the firewall/monitoring/logs roles (issue #24).")
    lines.append("")
    lines.append("---")
    lines.append("")

    # Subnets
    lines.append("## Subnets")
    lines.append("")
    lines.extend(render_subnets_table(group_vars))
    lines.append("")
    lines.append("---")
    lines.append("")

    # Per-host flows
    lines.append("## Per-host flows")
    lines.append("")
    lines.append("Inbound tables are rendered from each host's `firewall_extra_rules`; outbound "
                 "tables from `network_flows_outbound`. SSH and other cross-cutting flows are in "
                 "the cross-cutting section below, not repeated per host.")
    lines.append("")
    for host in hosts:
        meta = host_vars[host]["host_meta"]
        summary = str(meta.get("summary", "")).strip()
        heading = f"### {host}"
        if summary:
            heading += f" — {summary}"
        lines.append(heading)
        lines.append("")
        if meta.get("notes"):
            lines.append(f"> {str(meta['notes']).strip()}")
            lines.append("")
        rules = synthesize_router_inbound(host_vars[host]) + list(
            host_vars[host].get("firewall_extra_rules") or [])
        lines.append("**Inbound**")
        lines.append("")
        if rules:
            lines.extend(render_inbound_table(resolver, rules))
        else:
            lines.append("_No host-specific inbound rules (SSH-only via the standard allow set)._")
        lines.append("")
        outbound = host_vars[host].get("network_flows_outbound") or []
        lines.append("**Outbound**")
        lines.append("")
        if outbound:
            lines.extend(render_outbound_table(resolver, outbound))
        else:
            lines.append("_No noteworthy host-specific outbound beyond the cross-cutting flows._")
        lines.append("")
    lines.append("---")
    lines.append("")

    # Cross-cutting flows
    lines.append("## Cross-cutting flows")
    lines.append("")
    lines.append("N-to-M flows that are not a single host's inbound rule (DNS recursion, "
                 "monitoring scrape, SSH, logging, Vault, public ingress, WireGuard mesh, "
                 "and routine host egress).")
    valid_flow_hosts = frozenset(inv_hosts) if inv_hosts else frozenset(hosts)
    all_excludes = flows.get("all_excludes") or []
    for tok in all_excludes:
        if str(tok) not in valid_flow_hosts:
            raise ValueError(f"all_excludes token {tok!r} is not an inventory host")
    if all_excludes:
        lines.append("")
        lines.append(f"> `all` in the table below excludes {', '.join(str(t) for t in all_excludes)} "
                     "(firewall-unmanaged; their real flows are modelled explicitly).")
    lines.append("")
    lines.extend(render_cross_cutting_table(
        resolver, flows.get("cross_cutting_flows", []) or [], valid_hosts=valid_flow_hosts))
    lines.append("")
    lines.append("---")
    lines.append("")

    # External endpoints
    lines.append("## External endpoints")
    lines.append("")
    lines.append("Non-peer `from`/`to` tokens used above (external services, source realms, and "
                 "host-group aliases).")
    lines.append("")
    lines.extend(render_externals_table(externals))
    lines.append("")

    # Notes
    notes = flows.get("notes") or []
    if notes:
        lines.append("---")
        lines.append("")
        lines.append("## Notes")
        lines.append("")
        for note in notes:
            lines.append(f"- {str(note).strip()}")
        lines.append("")

    text = "\n".join(lines)
    if not text.endswith("\n"):
        text += "\n"
    return text


def build(inventory: Path = INVENTORY) -> str:
    group_vars, hosts_yml, flows, host_vars = load_inventory(inventory)
    return render_document(group_vars, hosts_yml, flows, host_vars)


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--inventory", type=Path, default=INVENTORY,
                        help="path to ansible/inventory (default: repo inventory)")
    parser.add_argument("--output", default=str(DEFAULT_OUTPUT),
                        help="output file, or '-' for stdout (default: docs/network-flows.md)")
    parser.add_argument("--check", action="store_true",
                        help="do not write; exit 1 if the committed doc is stale")
    args = parser.parse_args(argv)

    rendered = build(args.inventory)

    if args.check:
        current = Path(DEFAULT_OUTPUT).read_text() if Path(DEFAULT_OUTPUT).exists() else ""
        if current != rendered:
            sys.stderr.write(
                "docs/network-flows.md is stale — run scripts/render-network-flows.py\n"
            )
            return 1
        return 0

    if args.output == "-":
        sys.stdout.write(rendered)
    else:
        Path(args.output).write_text(rendered)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
