; /usr/local/etc/wireguard/wg1.conf — cr1.de1 wg1 -> rtr.ovh1 wg1
[Interface]
ListenPort = 1338
PrivateKey = <PRIVATE_KEY>

[Peer]
; rtr.ovh1 (OVH underlay endpoint)
PublicKey = 61i9efepALlk/+8bqtPSsVhJOuRam2F8/bbXv4VvgCI=
Endpoint = [2001:41d0:303:48a::2]:1338
AllowedIPs = ::/0
PersistentKeepalive = 30
