; /usr/local/etc/wireguard/wg2.conf — cr1.de1 wg2 -> cr1.ch1 wg2
[Interface]
ListenPort = 1342
PrivateKey = <PRIVATE_KEY>

[Peer]
; cr1.ch1 (underlay endpoint)
PublicKey = 6NHaepgMYrpvj9oY/ZmAMndZivjD6H4jwTIjWi5fEw4=
Endpoint = [2a09:4c0:100:2d88::8898]:1342
AllowedIPs = ::/0
PersistentKeepalive = 30
