; /usr/local/etc/wireguard/wg3.conf — cr1.nl1 wg3 -> rtr.ovh1 wg0
[Interface]
ListenPort = 1340
PrivateKey = <PRIVATE_KEY>

[Peer]
; rtr.ovh1 (OVH underlay endpoint)
PublicKey = 61i9efepALlk/+8bqtPSsVhJOuRam2F8/bbXv4VvgCI=
Endpoint = [2001:41d0:303:48a::2]:1337
AllowedIPs = ::/0
PersistentKeepalive = 30
