; /usr/local/etc/wireguard/wg4.conf — cr1.nl1 wg4 -> cr1.ch1 wg1
[Interface]
ListenPort = 1341
PrivateKey = <PRIVATE_KEY>

[Peer]
; cr1.ch1 (underlay endpoint)
PublicKey = G5AFwHYX6Z9KunKr92OsFDlq6y2UOy+6kvFRlmHAjg0=
Endpoint = [2a09:4c0:100:2d88::8898]:1341
AllowedIPs = ::/0
PersistentKeepalive = 30
