# Public interface #
ext_if="vtnet0"

# Set and drop these IP ranges on public interface #
table <bogons4> persist file "/etc/pf.bogons4"
table <bogons6> persist file "/etc/pf.bogons6"

## Skip loop back interface - Skip all PF processing on interface ##
set skip on lo
# Skip Wireguard mesh between servers
# Do not skip so WG traffic gets scrubbed properly
#set skip on wg

## Sets the interface for which PF should gather statistics such as bytes in/out and packets passed/blocked ##
set loginterface $ext_if
# Scrub packets
match all scrub(random-id max-mss 1360)

## Set default policy ##
block return in log all
block return out log all

# Drop Bogons
block drop in quick log on $ext_if inet from <bogons4>
block drop out quick log on $ext_if inet to <bogons4>
block drop in quick log on $ext_if inet6 from <bogons6>
block drop out quick log on $ext_if inet6 to <bogons6>

## Blocking spoofed packets
antispoof quick log for $ext_if

# Pass all traffic on WG - no state (asymmetric routing)
pass quick on wg all no state

# Transit traffic to/from our AS - no state (asymmetric routing)
pass in quick on $ext_if inet6 from any to 2a0c:b641:b50::/44 no state
pass out quick on $ext_if inet6 from 2a0c:b641:b50::/44 to any no state

# Wireguard
pass in quick on $ext_if inet proto udp from any to any port = 1337 keep state label "WG_RULE: Allow WG IPv4 wg0 cr1.de1"
pass in quick on $ext_if inet6 proto udp from any to any port = 1337 keep state label "WG_RULE: Allow WG IPv6 wg0 cr1.de1"
pass in quick on $ext_if inet proto udp from any to any port = 1338 keep state label "WG_RULE: Allow WG IPv4 wg1 gw01"
pass in quick on $ext_if inet proto udp from any to any port = 1340 keep state label "WG_RULE: Allow WG IPv4 wg3 rtr.ovh1"
pass in quick on $ext_if inet6 proto udp from any to any port = 1340 keep state label "WG_RULE: Allow WG IPv6 wg3 rtr.ovh1"
pass in quick on $ext_if inet6 proto udp from any to any port = 1338 keep state label "WG_RULE: Allow WG IPv6 wg1 gw01"
pass in quick on $ext_if inet proto udp from any to any port = 1340 keep state label "WG_RULE: Allow WG IPv4 wg3 rtr.ovh1"
pass in quick on $ext_if inet6 proto udp from any to any port = 1340 keep state label "WG_RULE: Allow WG IPv6 wg3 rtr.ovh1"

# External BGP
pass in quick on $ext_if inet6 proto tcp from 2a0c:b640:10::ffff to any port = bgp keep state label "BGP_RULE: Allow BGP from Servperso"

# SSH
pass in quick on $ext_if inet proto tcp from 77.166.211.126 to any port = ssh flags S/SA keep state label "USER_RULE: Allow SSH from KPN IPv4"
pass in quick on $ext_if inet6 proto tcp from 2a02:a442:1016::/48 to any port = ssh flags S/SA keep state label "USER_RULE: Allow SSH from KPN IPv6"

# Allow Ping
pass in quick on $ext_if inet proto icmp keep state
pass in quick on $ext_if inet6 proto ipv6-icmp keep state

# Allow any out
pass out quick on $ext_if inet proto { tcp, udp, icmp } from any to any keep state
pass out quick on $ext_if inet6 proto { tcp, udp, ipv6-icmp } from any to any keep state
